### ISSUE TITLE
show readme before dirs

### ISSUE THREAD

**Issue by zoumingzhe** [adrianschubek/dir-browser#10]
Now, the readme is after all dirs. I want to add a config option to show readme before dirs.

**Comment by adrianschubek** [comment]
Readme can now be rendered on top.
![image](https://github.com/adrianschubek/dir-browser/assets/19362349/5cfe60ce-0c64-4e72-8320-f7b96291b416)
https://dir.adriansoftware.de/v3/configuration/
Will be published in next release v3.2.
