### ISSUE TITLE
add a icon for website

### ISSUE THREAD

**Issue by zoumingzhe** [adrianschubek/dir-browser#14]
It's always inconvenient for me to deploy multiple dockers without icons.

**Comment by zoumingzhe** [comment]
We need to have at least one default icon, and it's best to allow the icon file to be mounted.

**Comment by adrianschubek** [comment]
You mean a custom favicon, right? 
![image](https://github.com/adrianschubek/dir-browser/assets/19362349/458b78fc-7412-4358-8496-85bc3f60c4fc)
This is a good idea.

**Comment by zoumingzhe** [comment]
yes

> You mean a custom favicon, right? ![image](https://private-user-images.githubusercontent.com/19362349/340025700-458b78fc-7412-4358-8496-85bc3f60c4fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0ODQ4NDQsIm5iZiI6MTcxODQ4NDU0NCwicGF0aCI6Ii8xOTM2MjM0OS8zNDAwMjU3MDAtNDU4Yjc4ZmMtNzQxMi00MzU4LTg0OTYtODViYzNmNjBjNGZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE1VDIwNDkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlYjYzYzNjMjYyNGRmODc3MzNiYzNiNzRhYzkzZTliNTRiZWMzOWE3MWNjNDM3ZDJhOGViZmY2ZTI4OGRkMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dvmrVtFptGF6pEBKjobNSNbu5oFvvgBimRSyUbI0Vt0) This is a good idea.

**Comment by adrianschubek** [comment]
I noticed that it should already work. When you mount a folder `-v /foobar:/var/www/html/public` then place the icon in `/foobar/favicon.ico` and it will be displayed on all pages. 
![image](https://github.com/adrianschubek/dir-browser/assets/19362349/aafb4993-9512-4e10-b26a-99024a06d19d)

You can also hide the favicon.ico in the file browser by creating a `/foobar/favicon.ico.dbmeta.json` with the content
```json
{
"hidden": true
}
```

**Comment by zoumingzhe** [comment]
can load the icon from .favicon.ico, we can default hidden all files and folders that starting with "."

**Comment by adrianschubek** [comment]
> we can default hidden all files and folders that starting with "."

It is possible to hide all files starting with a dot using `-e IGNORE=".*"` https://dir.adriansoftware.de/v3/configuration/ignore#examples

**Comment by zoumingzhe** [comment]
> > we can default hidden all files and folders that starting with "."
> 
> It is possible to hide all files starting with a dot using `-e IGNORE=".*"` https://dir.adriansoftware.de/v3/configuration/ignore#examples But yes I need to improve the documentation.

great
