### ISSUE TITLE
add password protection for entire folders

### ISSUE THREAD

**Issue by adrianschubek** [adrianschubek/dir-browser#17]

**Comment by zoumingzhe** [comment]
From my perspective, most users using dir-browser do not require password protection, and even if password protection is needed, it should be reinforcing the entire website.
Such fine-grained access control is cumbersome and prone to errors (such as renaming causing password protection to fail), and too many passwords are also easy to forget.
If we can have unified authentication for the website (such as oauth, ldap, etc.), this would be useful. If users want to control access to folders or folders, my suggestion is to deploy multiple instances through Docker and configure different policies.

**Comment by adrianschubek** [comment]
Yeah, I agree. This feature was intended for some small scale deployments where the folder structure stays the same. A unified approach with different providers like you suggested sounds good. Will look into it.
