### ISSUE TITLE
Incorrect relative link redirection in readme

### ISSUE THREAD

**Issue by zoumingzhe** [adrianschubek/dir-browser#20]
I have the following directory structure:

```
/root
/root/A/B/file
/root/A/B/readme
/root/A/readme
/root/readme
``` 

There is a relative link `B](./B)` in `/root/A/readme` (`example.com/A`). When I clicked on the link, I was redirected to` example. com/B`, and I am looking forward to redirecting to `example. com/A/B`.

I believe this is a problem that can be solved. Because relative links can be redirected correctly in the GitHub repository.

**Comment by adrianschubek** [comment]
The issue was a missing slash `/` for folders in the URL. Fixed it.

**Comment by zoumingzhe** [comment]
The image in readme cannot be loaded. This should be the same issue, and I will confirm whether the issue still exists in version 3.3.
