### ISSUE TITLE
cannot preview pdf when + in filename

### ISSUE THREAD

**Issue by zoumingzhe** [adrianschubek/dir-browser#23]
**Describe the bug**
I cannot preview the pdf file (ThinkVision+P27h-20.pdf).

**Expected behavior**
I hope to preview `ThinkVision+P27h-20.pdf`.

**Screenshots**
![image](https://github.com/adrianschubek/dir-browser/assets/23275497/67cbaacb-825e-4cdf-8420-3cda7db2badd)
![image](https://github.com/adrianschubek/dir-browser/assets/23275497/241810a3-a017-429f-817a-af91c27e36e7)

**Environment**
dir-browser 3.2

**Additional context**
When I rename the pdf file to `ThinkVision.pdf`, I can preview it.

**Comment by adrianschubek** [comment]
Thanks for your report. I can reproduce it and fixed it. It was caused by `urldecode()`
![image](https://github.com/adrianschubek/dir-browser/assets/19362349/310241dd-4593-4327-9438-7ea3fad53ca5)
