### ISSUE TITLE
cannot download 660 permission files

### ISSUE THREAD

**Issue by zoumingzhe** [adrianschubek/dir-browser#33]
**Describe the bug**

Run docker as root user, like: `docker run --user 0:0`.
Can browse folders and files with 660 permissions normally, but reports a 403 error when downloading.

**To Reproduce**
1. Click to download
2. Report 403 error

**Expected behavior**

Download 660 permission file normally.

**Screenshots**

File Status:
![de91e285e29b03d98451b985da3e734](https://github.com/user-attachments/assets/b5a9a9ca-feb6-4b8c-a8ec-bcede7081cf0)

Browse files:
![abcaec34e1c041abc9f310cc1d1969d](https://github.com/user-attachments/assets/b3911373-01d7-41ef-9d47-95207ca9f8c0)

Click to download:
![7d1fcf1ae35749870247a29c36b805d](https://github.com/user-attachments/assets/b3d3051e-7cbe-4652-a8f3-4b2a1cf36ce0)

**Environment**

- <ins>dir-browser version: 3.7.0 (docker)      </ins>
 - OS: Windows
 - Browser: Chrome

**Comment by zoumingzhe** [comment]
I changed umask to 007.

**Comment by adrianschubek** [comment]
Thanks for the report. I fixed it.
