### ISSUE TITLE
Manual deployment (no docker)

### ISSUE THREAD

**Issue by wxnnvs** [adrianschubek/dir-browser#9]
**Is your feature request related to a problem? Please describe.**
I would like to host this without using docker

**Describe the solution you'd like**
A setup.php file or smt

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by adrianschubek** [comment]
Hey. If you want to use it without docker you would have to setup and configure redis, nginx, supervisor, utpp, php manually which is quite some work. This is why I decided to use Docker to package everything in a single image to make it as easy as possible to use without having to worry about installing and configuring tons of stuff. 
This project also relies on the networking and security features from Docker to make it very fast and secure.
Also, what is your use-case where you cannot use docker?

**Comment by wxnnvs** [comment]
I don't have a vps
I was searching for a php filemanager as i only have basic webhosting
Thank you anyways
